### PR TITLE
New benchmarks for half/quarter-width bins

### PR DESCRIPTION
**Pull request by damonge**
@c-d-leonard here are the new benchmarks. I haven't yet had time to do any visual checks, but hopefully there are no catastrophes.

### CODE REVIEW

**Comment by c-d-leonard** [comment]
I just did some visual checks on these and quite a few of them have some wiggles that look like they might be numerical artefacts indicating higher res might be needed. Eg here for what I think is the lowest z autocorr bin
C_ell_artifacts
@damonge

**Comment by c-d-leonard** [comment]
C_ell_gs_wiggles
here's one from galaxy-galaxy lensing just as another example

**Comment by damonge** [comment]
OK, @c-d-leonard , I've looked at the benchmarks comparing them with Limber and I find the following:
- Most (or all) of the clearly numerical wiggles happen for the quarter bins (which makes sense)
- In the galaxy-galaxy correlations, it mostly happens for x-corrs between bins with little overlap. This also makes sense, but the good news is that these should contribute little to the total SN (although "little" is a very relative word when we're talking about the LSST sensitivity...).
- In the galaxy-shear correlations, the noise mostly happens for "unphysical" bins where the lenses are behind the sources. This again makes sense, and their contribution should be "little".

In any case, I'm rerunning all these benchmarks with a higher resolution integral in log(k). I'll compare the results with these and get back to you.

**Comment by damonge** [comment]
Update on this: the more accurate benchmarks do mitigate these wiggles, probably enough to make them irrelevant (I haven't quantified it yet). I'm running yet-more-accurate benchmarks now, and will do the numbers (check relative chi2s) to make sure they're fine before we merge.

**Comment by damonge** [comment]
@c-d-leonard ok, much higher precision benchmarks in. Most of these issues have gone away. Some of the power spectra are still a bit wiggly, but they are the weird ones (e.g. last clustering bin with first source bin) and I don't think they matter. I'll be happy to revisit this if we are convinced that this is an issue after comparing with the other non-Limber methods

**Comment by c-d-leonard** [comment]
thanks, happy to merge!

**Review by c-d-leonard — APPROVED** [review]
looks good

**Pull request merged**
