### PR TITLE
Brute force benchmarks

### PR DESCRIPTION
**Pull request by damonge**
This PR adds:
- Non-Limber benchmarks from a modified version of CCL that implements a slow brute-force approach. The benchmarks use this up to ell=1000. I may update these files after an even higher-precision run, but I think they should be OK for the current SRD data vector.
- A tester class and an accompanying `example_benchmark.py` that shows how the outputs of a given entry will be compared with the benchmarks.

### CODE REVIEW

**Comment by c-d-leonard** [comment]
@damonge thanks! One thing: when I run the new example_benchmarks.py with CCL master I get an error about `AttributeError: 'Cosmology' object has no attribute '_set_linear_power_from_arrays'`. Is this assuming the release version of CCL?

**Comment by damonge** [comment]
Oh, that's the old version of CCL (before the calculator mode). Give me a sec.

**Comment by damonge** [comment]
Try again?

**Review by c-d-leonard — APPROVED** [review]
Looks good now! Thanks.

**Pull request merged**
